### PR TITLE
fix(eda): fix the plot doesn't show up

### LINKED ISSUE #102: dataprep plot() doesn't show plots on the Google Colab interface.
I used dataprep on google colab for one  of my EDA work. The dataprep library works well on google colab but doesn't shows up the plots.

### PR DESCRIPTION
**Pull request by dovahcrow**
# Description

Previously the Report class is rendered with the whole HTML documentation from bokeh `save`. This will inject duplicate bokeh scripts which cause problem.

fixes #102 #147 

# How Has This Been Tested?

Manually

# Snapshots:

No snapshots.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have already squashed the commits and make the commit message conform to the project standard.
- [x] I have already marked the commit with "BREAKING CHANGE" or "Fixes #" if needed.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dovahcrow** [comment]
@peterirani Hi Peter, could you please help me check if the issue 102 and 147 is fixed by this patch?

**Comment by dovahcrow** [comment]
We monkey patched the javascript code from bokeh to let it wait for 1 sec if Bokeh is not loaded -- super tricky.

**Comment by peterirani** [comment]
Hi Young, the BokehJS library still does not show up after reloading. 
Screen Shot 2020-06-28 at 9 31 32 PM

**Comment by peterirani** [comment]
It is working now! previously I had not updated the poetry dependencies.

**Pull request merged**
