### PR TITLE
feat(connector):from_key parameter validation

### PR DESCRIPTION
**Pull request by pallavibharadwaj**
The PR is addressing two issues:

### **1. Parameter validation for template params:**
Parameter checking happens in dataprep `connector.py` where we check for keys in `allowed_params`. This check had to include the `from_key` to accommodate for the template params.

_Also Fixed_: Finnhub config files had the template keys mentioned differently (the `fromKey` was being passed as part of the query). This has been fixed now on the DataConnector repo along with the corresponding changes in the DBLP config files. [Needs merge of the [corresponding PR in the Data Connector repo](https://github.com/sfu-db/DataConnectorConfigs/pull/50).]

**Testing**:
`fromKey` tested in both DBLP and Finnhub.
The following was throwing an error because `first_name` and `last_name` are not directly specified as params in the config file.
`df = await dc.query("publication", first_name="Jian", last_name="Pei")`

Selection_050

**Consequence**:
In the config files, the `fromKey` in the template param `FieldDef` is now to be specified as a `List` instead of `string` containing all the params the template needs.
Ex:
`
"fromKey": ["first_name", "last_name"]
`
Note: Single parameter for template should have the key specified an array of one element.

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
### **2. Reducing Dependency on Requests Library** [#396]:
Replacing the python requests library with our own implementation serving as a wrapper around the standard `http.client` library

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have already squashed the commits and make the commit message conform to the project standard.
- [x] I have already marked the commit with "BREAKING CHANGE" or "Fixes #" if needed.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by peiwangdb — COMMENTED** [review]
Is it possible for us to write our own request function in a separate utils file and make the interface similar to the original request function, instead of substituting the code in all the places? @pallavibharadwaj

**Comment by pallavibharadwaj** [comment]
> Is it possible for us to write our own request function in a separate utils file and make the interface similar to the original request function, instead of substituting the code in all the places? @pallavibharadwaj

Is this for the requests library substitution? Yes, sure. I'll work on that.

**Comment by peiwangdb** [comment]
@pallavibharadwaj would you fix the check failures?

**Comment by pallavibharadwaj** [comment]
> @pallavibharadwaj would you fix the check failures?

@peiwangdb The check is for code format with `connector.py` that does not include my changes. Re-formatting the file will result in a lot of code changes in that file. I did not do it so it will be easier to review my particular changes. Do you want to re-format the whole file?

**Comment by peiwangdb** [comment]
@pallavibharadwaj thanks for the information. I am not sure why this formatting issue emerged. Do you have an idea who made the changes? If it is not a hard fix, could you open a new PR to solve the issue and then do a rebase? I can quickly approve of it.

**Comment by nick-zrymiak** [comment]
> > @pallavibharadwaj would you fix the check failures?
> 
> @peiwangdb The check has failed for code formatting with `connector.py` that does not include my changes. Re-formatting the file will result in a lot of code change in this file. I did not do it so it will be easier to review the particular changes pertaining to this issue. Do you want me to go ahead and reformat the whole file?

What would be the alternative to this?

**Comment by pallavibharadwaj** [comment]
@peiwangdb @nick-zrymiak 

1. It's a simple fix and I have re-formatted the connector file along with all the other files that needed reformatting as a separate PR #450 

2. There is one other issue that I had discussed on Discord regarding security warning with HTTPSConnection on older versions of Python (prior to 2.7.9 and 3.4.3). We have to make a choice here depending on what versions of Python we support for Dataprep. If we support later than the above-mentioned versions, we can probably ignore this warning.

https_security

**Comment by nick-zrymiak** [comment]
> @peiwangdb @nick-zrymiak
> 
> 1. It's a simple fix and I have re-formatted the connector file along with all the other files that needed reformatting as a separate PR #450
> 2. There is one other issue that I had discussed on Discord regarding security warning with HTTPSConnection on older versions of Python (prior to 2.7.9 and 3.4.3). We have to make a choice here depending on what versions of Python we support for Dataprep. If we support later than the above-mentioned versions, we can probably ignore this warning.

I've noticed the cutoff for other large Python libraries is 3.6 so may be fine.

There's also this paragraph from an article that came out Feb 6, 2019 so the numbers may be more lopsided now:

"Regarding Python 2 vs. Python 3 adoption, the survey shows 84 percent using Python 3 and 16 percent still using Python 2. Among the Python 3 users, 54 percent are using Python 3.6 and 30 percent Python 3.7, with the rest split among other versions."

On the other hand there may be a substitute for HTTPSConnection but I'm not too sure.

@peiwangdb what do you think?

**Comment by pallavibharadwaj** [comment]
@peiwangdb @dovahcrow I have resolved the issues with the PR. Like I said before, there is still a security warning with HTTPSConnection on older versions of Python (prior to 2.7.9 and 3.4.3), which we discussed can be ignored.

**Review by nick-zrymiak — APPROVED** [review]
Very well done!

**Pull request merged**
