### PR TITLE
docs(data_connector): documentation update

### PR DESCRIPTION
**Pull request by kla55**
# Description

Created 3 tutorials for data connector: Yelp, DBLP, and Spotify. In addition, I updated to index.rst and images folder. 

# How Has This Been Tested?

N/A

# Snapshots:

N/A

# Checklist:

- [X] My code follows the style guidelines of this project
- [ ] I have already squashed the commits and make the commit message conform to the project standard.
- [ ] I have already marked the commit with "BREAKING CHANGE" or "Fixes #" if needed.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by kla55** [comment]
Update examples and docs folder to include new tutorial section

**Comment by peiwangdb** [comment]
Thanks! Please edit the commit message based on instructions here since it will be included in the release note: https://github.com/sfu-db/dataprep/wiki/Coding-rules
With this minor change, I think it's good to go.

**Comment by kla55** [comment]
@peiwangdb please review again. 

Thanks

**Comment by peiwangdb** [comment]
@dovahcrow  Can you double chek the changes and conflicts here so that we can safely include this PR in the coming release?

**Comment by dovahcrow** [comment]
@kla55 Please add me to the collaborators of your forked repo and I'll do the code migration for you.

**Comment by kla55** [comment]
Hi @dovahcrow,

I added you as a collaborator to my repo.

**Comment by dovahcrow** [comment]
Please run `git fetch && git reset --hard origin/klau_dataprep` if origin is your repo alias.

**Pull request merged**
