### PR TITLE
Implement clean json

### PR DESCRIPTION
**Pull request by yixuy**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**This PR is focusing on adding the feature for clean JSON, which makes the JSON file split into more columns for user to use.**

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

```
import pandas as pd
import numpy as np
df = pd.DataFrame({"Name":
                   ["Abby", "Scott", "Scott", "Scott2", np.nan, "NULL"],
                   "AGE":
                   [12, 33, 33, 56,  np.nan, "NULL"],
                   "weight__":
                   [32.5, 47.1, 47.1, 55.2, np.nan, "NULL"],
                   "Admission Date":
                   ["2020-01-01", "2020-01-15", "2020-01-15",
                    "2020-09-01", pd.NaT, "NULL"],
                   "email_address":
                   ["abby@gmail.com","scott@gmail.com", "scott@gmail.com", "test@abc.com", np.nan, "NULL"],
                   "Country of Birth":
                   ["USA","Canada", "Canada", "NULL", np.nan, "NULL"],
                  "Contact (Numbers)":
                   ["1-789-456-0123","1-123-456-7890","1-123-456-7890","86-456-123-7890", np.nan, "NULL" ],
                   "address": [
                        "123 Pine Ave.",
                
                        "1234 west main heights 57033",
                        "apt 1 789 s maple rd manhattan",
                    
                        "1111 S Figueroa St, Los Angeles, CA 90015",
       
                        np.nan,
                        "NULL"
                    ],
                   'url': ['https://github.com/sfu-db/dataprep'
                    ,'https://github.com/sfu-db/dataprep',  
                    'https://github.com/sfu-db/dataprep' , 
                    'https://github.com/sfu-db/dataprep',
                    'https://github.com/sfu-db/dataprep',
                    'https://github.com/sfu-db/dataprep' ],
                   "messy_json": [
                  '{"name": "jane doe", "salary": 9000, "email": "jane.doe@prative.com"}',
                  '{"name": "doe", "salary":8000, "email": "hello@prative.com"}',
                  '{"name": "Doe", "salary": 200, "email": "google@prative.com"}',
                  '{"name": "Fire", "salary": 11000, "email": "jane@prative.com"}',
                  '{"name": "Sam", "salary": 4000, "email": "doe@prative.com"}',
                  '{"name": "Ethan", "salary": 2000, "email": "Research@prative.com"}'
                        ]
})
df
clean_json(df, "messy_json")
```

# Snapshots:
image

Include snapshots for easier review.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have already squashed the commits and made the commit message conform to the project standard.
- [ ] I have already marked the commit with "BREAKING CHANGE" or "Fixes #" if needed.
- [X] I have performed a self-review of my own code
- [X] I have commented on my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by qidanrui** [comment]
Can we handle nested Json like '{"name": {"first_name": "jane", "last_name": "doe"}, "salary": 9000, "email": "jane.doe@prative.com"}'

**Comment by yixuy** [comment]
> 

1`

**Comment by yixuy** [comment]
I think it will handle this nested case
the result is as follows
The name will be **Nan** and there are more columns called **first name and last name**
Correct me if there is anything wrong
image

**Comment by qidanrui** [comment]
> I think it will handle this nested case the result is as follows The name will be **Nan** and there are more columns called **first name and last name** Correct me if there is anything wrong image

Hmmm, first name and last name are NaNs ?

**Comment by yixuy** [comment]
> > I think it will handle this nested case the result is as follows The name will be **Nan** and there are more columns called **first name and last name** Correct me if there is anything wrong image
> 
> Hmmm, first name and last name are NaNs ?

The test cases are as follows:
image

image


The case you have mentioned is an object for the name field **"name": {"first_name": "jane", "last_name": "doe"}**  Therefore, it will be split new field called the **first_name** and **last_name** and leave NaN in the name field. By contrast, if the name field is like **"name": "jane doe"**. It will filled in the name field rather than NaN. Please let me know if I understand incorrectly, thank you!

**Comment by qidanrui** [comment]
> > > I think it will handle this nested case the result is as follows The name will be **Nan** and there are more columns called **first name and last name** Correct me if there is anything wrong image
> > 
> > 
> > Hmmm, first name and last name are NaNs ?
> 
> The test cases are as follows: image
> 
> image
> 
> The case you have mentioned is an object for the name field **"name": {"first_name": "jane", "last_name": "doe"}** Therefore, it will be split new field called the **first_name** and **last_name** and leave NaN in the name field. By contrast, if the name field is like **"name": "jane doe"**. It will filled in the name field rather than NaN. Please let me know if I understand incorrectly, thank you!

Great! After reviewing the code, I think we can merge it~

**Review by qidanrui — APPROVED** [review]

**Pull request merged**
