### PR TITLE
feat(plot_missing) : add a dendrogram for plot missing

### PR DESCRIPTION
**Pull request by peterirani**
# Description

I have tried to implement a dendrogram plot for the plot_missing module. Bokeh does not have an inbuilt dendrogram functionality. **The approach I have used is as follows:**
1) Use scipy and matplotlib to render the dendrogram image and Generate a RGBA numpy array of the image. This is done in the compute.py of the missing module.
3) Finally render the RGBA array using Bokeh, in render.py of the missing module.

Currently the resolution of the plot is **not** optimal and the matplotlib image also gets rendered below the bokeh image. I have tried to remove the matplotlib image but keeps showing up. I have attached a screenshot below. 

Screen Shot 2020-07-24 at 10 55 31 PM

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

I have tested this on the titanic dataset and a few other datasets, it seems to work but the resolution is again not optimal and matplotlib image shows below.

# Snapshots:

Include snapshots for easier review.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have already squashed the commits and make the commit message conform to the project standard.
- [x] I have already marked the commit with "BREAKING CHANGE" or "Fixes #" if needed.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by peterirani** [comment]
Update - trying to render this using Bokeh and Scipy.

**Comment by peterirani** [comment]
The dendrogram using Bokeh renders fine but if we re-run the cell, matplotlib image also gets rendered. 

** first time when you run the cell**
Screen Shot 2020-07-30 at 10 56 16 PM

**once you re-run the cell
Screen Shot 2020-07-30 at 10 56 28 PM

I can't figure out why the image (I think it is matplotlib) is being rendered.

**Comment by peterirani** [comment]
Thanks, Brandon `no_plot` works! I will work on the hover tips, and 50 columns issues now.

**Comment by peterirani** [comment]
Benchmark timing before and after adding missing_dendrogram plot. 

**BEFORE**
Screen Shot 2020-08-06 at 11 09 17 AM


**AFTER**
Screen Shot 2020-08-06 at 11 04 51 AM

**Comment by dovahcrow** [comment]
Add some optimizations. On my machine, 5M rows adult dataset
Before:
CPU times: user 10.1 s, sys: 2.06 s, total: 12.2 s
Wall time: 7.46 s
After:
CPU times: user 4.94 s, sys: 768 ms, total: 5.71 s
Wall time: 3.07 s

@peterirani I think your commit message is wrong. There should not be a space between ")" and ":". Otherwise, the release note will not be shown correctly as mentioned on discord 2 weeks ago. I've revised the commit message.

**Comment by peterirani** [comment]
Thank you Young, Brandon and I are working on the documentation for dendrogram.

**Pull request merged**
