### PR TITLE
fix(eda): fixed bugs come with random generated datasets

### PR DESCRIPTION
**Pull request by eutialia**
# Description

Fixed bugs come with random generated datasets

# How Has This Been Tested?

CI

# Snapshots:

N/A

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have already squashed the commits and make the commit message conform to the project standard.
- [x] I have already marked the commit with "BREAKING CHANGE" or "Fixes #" if needed.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jinglinpeng** [comment]
@brandonlockhart  Could you please help review the change of `clean_country`?

**Comment by brandonlockhart** [comment]
@jinglinpeng the changes to `clean_country` look good.

**Review by jinglinpeng — DISMISSED** [review]

**Comment by jinglinpeng** [comment]
Looks good!

**Comment by jinglinpeng** [comment]
The PR looks good! @eutialia  Could you also add test on the random dataframe to cover the changed code? E.g.,
image

**Comment by eutialia** [comment]
Updated.

**Review by jinglinpeng — APPROVED** [review]

**Pull request merged**
