### PR TITLE
feat(clean): clean latitude, longitude coordinates

### PR DESCRIPTION
**Pull request by brandonlockhart**
# Description

Function to clean latitude and longitude coordinates. 

# How Has This Been Tested?

# Snapshots:

Functionality:
Screen Shot 2020-08-26 at 1 32 50 PM

specify output format
Screen Shot 2020-08-26 at 1 35 22 PM

split into two columns
Screen Shot 2020-08-26 at 1 36 47 PM

split and specify the format
Screen Shot 2020-08-26 at 1 38 10 PM

Clean only one coordinate
Screen Shot 2020-08-26 at 1 39 35 PM

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have already squashed the commits and make the commit message conform to the project standard.
- [ ] I have already marked the commit with "BREAKING CHANGE" or "Fixes #" if needed.
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by yxie66 — COMMENTED** [review]
Great PR! @brandonlockhart  I have two questions regarding to the error handling mechanism of cleaning component. 

First, in your current implementation, if the error type is set to "raise", then as long as there is one value out of the whole column which can't be parsed, error will be raised. Would it be a little bit too strict for users if they want to analyze a really big dataset? Maybe they want some parameters like "minimum_broken_data_percentage_to_raise_error" to gain control of such situation.

Second, when applying cleaning function, currently you let all instance pass the validator at first, if they don't pass, they will be recognized as "unknown". Will it make our tool lose some flexibility to do some basic cleaning for users? In my opinion, I think it depends on the data type. For long/lat maybe your current solution is good, but for other types where typos happen frequently in initial input, we may figure out other method to fix that. 

Thank you very much and let me know for any comments/suggestions!

**Comment by brandonlockhart** [comment]
> First, in your current implementation, if the error type is set to "raise", then as long as there is one value out of the whole column which can't be parsed, error will be raised. Would it be a little bit too strict for users if they want to analyze a really big dataset? Maybe they want some parameters like "minimum_broken_data_percentage_to_raise_error" to gain control of such situation.

The user can run `df["col"][~validate_lat_long(df["col"])].sum()/len(df)` to determine whether they want to set `errors="ignore"` in `clean_lat_long()`, however you're right that this could be slow on large data. I think that people will generally use `errors="raise"` when they do not expect there to be any invalid lat/long coordinates and therefore would want to identify any problems, and manually fix them. So in my opinion, we can wait until this feature is requested by an external user before we implement it.

> Second, when applying cleaning function, currently you let all instance pass the validator at first, if they don't pass, they will be recognized as "unknown". Will it make our tool lose some flexibility to do some basic cleaning for users? In my opinion, I think it depends on the data type. For long/lat maybe your current solution is good, but for other types where typos happen frequently in initial input, we may figure out other method to fix that.

Can you please give an example of this scenario that we would not support: "Will it make our tool lose some flexibility to do some basic cleaning for users?" There are two approaches that I think are related to your second comment:
1. We encourage users to create an issue when our tool fails for their task (like [usaaddress](https://github.com/datamade/usaddress#bad-parses--bugs) does)
2. We give the user the control to define the format, like [here](https://www.codeproject.com/Articles/15659/Longitude-Latitude-String-Parser-and-Formatter)

I prefer to use point 1. for now and perhaps implement point 2. later if requested. 

These are just my thoughts, let me know what you think we should do @yxie66, and please let us know any other opinions @jnwang @dovahcrow

**Comment by yxie66** [comment]
> > Second, when applying cleaning function, currently you let all instance pass the validator at first, if they don't pass, they will be recognized as "unknown". Will it make our tool lose some flexibility to do some basic cleaning for users? In my opinion, I think it depends on the data type. For long/lat maybe your current solution is good, but for other types where typos happen frequently in initial input, we may figure out other method to fix that.
> 
> Can you please give an example of this scenario that we would not support: "Will it make our tool lose some flexibility to do some basic cleaning for users?" There are two approaches that I think are related to your second comment:
> 
> 1. We encourage users to create an issue when our tool fails for their task (like [usaaddress](https://github.com/datamade/usaddress#bad-parses--bugs) does)
> 2. We give the user the control to define the format, like [here](https://www.codeproject.com/Articles/15659/Longitude-Latitude-String-Parser-and-Formatter)
> 
> I prefer to use point 1. for now and perhaps implement point 2. later if requested.
> 
> These are just my thoughts, let me know what you think we should do @yxie66, and please let us know any other opinions @jnwang @dovahcrow

For the first question I agree with you that we can wait for real users to determine whether it's necessary. For the second part, for the customized format thing I agree with you, what I'm referring to there is some cases with minor and obvious typo, like we discussed last time, something like "y i@sfu.ca". If we refuse even raise errors for such cases, maybe that's way too strict? So currently I plan to do some basic cleaning before passing values to validator, like removing whitespaces. But it may depends on the semantic type we are going to check, I think. So basically I think this PR is good for now to be approved, then we can adjust to real users' opinions. How do you think?

**Comment by brandonlockhart** [comment]
I understand your second point now, thanks. Like you said, I think it depends on the semantic type. I think we can look at how other approaches parse values and do any cleaning before parsing that seems reasonable. Unless you can find such an example problem (like "y i@sfu.ca" for emails) for geographic coordinates, I think the current code is okay.

**Comment by jnwang** [comment]
Great discussion!

Regarding Q1, I agree with you guys.

Regarding Q2, what would happen if the value starts with white space, such as “  60°”?

Maybe we can introduce an argument called “fuzzy” in the future. By default, it is set to False. 

`Fuzzy = False`
- Validate() will do the strict checking. So it will return False for “  60°”
- Clean() will not clean it.

`Fuzzy = True`
- Validate() will return True if and only if it contains lat/long. So it returns True for “  60°”
- Clean() will extract lat/long from the string. Clean() returns “60°”

We don’t have to have it for now, but I think we should make Validate() and  Clean() consistent.

In this case of `Fuzzy = False`, the design of clean_lat_long() is fine. The design of clean_email() needs to be revised a little bit. That is, we will not clean email If it does not pass validate_email()

`dateutil` adopts a similar design. See https://dateutil.readthedocs.io/en/stable/parser.html

**Comment by brandonlockhart** [comment]
Right now, `clean_lat_long()` will match " 60°" since the regex matches an arbitrary amount of whitespace before and after each component (so does GeoPy, [regex](https://github.com/geopy/geopy/blob/1c1cfd516c095abc38fe3ff00d82071d0290edaf/geopy/point.py#L17)).

I like this "fuzzy" idea, the challenge I see is defining the set of all "fuzzy" and "non-fuzzy" geo-coordinate representations (many [valid representations](https://geopy.readthedocs.io/en/stable/#geopy.point.Point.from_string)). I think for now I can stop matching leading and trailing whitespace (so " 60°" will be invalid) which will be the `fuzzy=False` case.

I agree that we can start by not cleaning the email before parsing, and that clean() and validate() should be consistent. And we can perhaps think more about what a fuzzy/non-fuzzy match should be for the different semantic types.

**Comment by yxie66** [comment]
PR merged. Thank you for the discussion!

**Pull request merged**
