### PR TITLE
docs(connector): update info function documentation

### PR DESCRIPTION
**Pull request by nick-zrymiak**
# Description

Modified info documentation. Add sections to connector overview and tutorial rst files.

# How Has This Been Tested?

Manually

# Snapshots:

image

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have already squashed the commits and make the commit message conform to the project standard.
- [x] I have already marked the commit with "BREAKING CHANGE" or "Fixes #" if needed.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by peiwangdb** [comment]
@juandavidospina Could you review the code and handle the conflicts according to our previous discussion? Thanks!

**Comment by juandavidospina** [comment]
@nick-zrymiak @peiwangdb 
Hi Nick, after reviewing your changes and after working on the new section of the user guide, I consider that the current "tutorial" sections should be maintained in the new version of the user guide section. That is, there will be three new pages: authorization, concurrency and pagination, plus these existing tutorial pages, so it is OK that you update them. Also, I will manually incorporate and adapt (if needed) your changes into the new pages for consistency purposes. Therefore, I approve your updates.

**Review by juandavidospina — DISMISSED** [review]
@nick-zrymiak @peiwangdb
Hi Nick, after reviewing your changes and after working on the new section of the user guide, I consider that the current "tutorial" sections should be maintained in the new version of the user guide section. That is, there will be three new pages: authorization, concurrency and pagination, plus these existing tutorial pages, so it is OK that you update them. Also, I will manually incorporate and adapt (if needed) your changes into the new pages for consistency purposes. Therefore, I approve your updates.

**Comment by peiwangdb** [comment]
Thanks @juandavidospina!  Could you add your approval review and I'll merge it.

**Comment by peiwangdb** [comment]
@nick-zrymiak for this PR, could you just include the files related to the info documentation update? That is, you open a new branch the same as the current develop branch and only commit the PR related changes. I noticed the connector code is also included.

**Comment by nick-zrymiak** [comment]
Yes!

**Review by peiwangdb — APPROVED** [review]

**Comment by peiwangdb** [comment]
@juandavidospina I've merged Nick's changes. Please pull the latest docs to work with, thanks!

**Pull request merged**
