### PR TITLE
fix(eda.plot): fix singular value for KDE and QQ norm plot

### LINKED ISSUE #150: plot(df, x) error
**Describe the bug**
The bug happened when running plot(df, x). It may be related to datatype. 

**Screenshots**
The dataset can be downloaded from [this link](https://www.dropbox.com/s/mv1waxnimiqxw35/flight_small.csv).

Screen Shot 2020-05-08 at 8 41 30 PM

### PR DESCRIPTION
**Pull request by eutialia**
Fixed #150 
# Description

Histogram with KDE and Q-Q plot will no longer show up when a singular value is given.

# How Has This Been Tested?

Added a singular value series in test DataFrame and a corresponding test scenario.

# Snapshots:

N/A

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have already squashed the commits and make the commit message conform to the project standard.
- [x] I have already marked the commit with "BREAKING CHANGE" or "Fixes #" if needed.
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jinglinpeng** [comment]
Good job! Please make the commit msg more informative as it will be included in the release log: `fix(eda.plot): fix singular value for KDE and QQ norm plot`. Other parts looks good to me.

**Comment by eutialia** [comment]
Commit message updated.

**Comment by jinglinpeng** [comment]
The circleci is failed due to black format issue. Please run `poetry run black dataprep` to fix this issue.

**Comment by eutialia** [comment]
Format issue fixed.

**Pull request merged**
